[build]
  publish = "."

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
